[package]
name = "app"
version = "0.1.1"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
tracing = "0.1.44"
async-trait = "0.1.86"
secrecy = "0.10.3"
bon = "3.8.2"
snafu = "0.8.9"
uuid = "1.12.1"
nutype = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
statum = "0.5.4"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
