[package]
name = "infra"
version = "0.1.1"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
app = { path = "../app" }

sqlx = { version = "0.8.6", features = [
  "postgres",
  "runtime-tokio",
  "macros",
  "migrate",
  "time",
  "uuid",
] }
utils = { path = "../utils" }
reqwest = { version = "0.13.2", features = ["json"] }
tracing = "0.1.44"
snafu = "0.9.0"
argon2 = "0.5.3"
async-trait = "0.1.89"
uuid = { version = "1.23.0", features = ["v4"] }
bon = "3.9.1"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
nutype = { workspace = true }
aes-gcm = "0.10.3"
secrecy = "0.10.3"
sha2 = "0.11.0"

[dev-dependencies]
axum = { version = "0.8.8" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
