[package]
name = "utils"
version = "0.1.1"
edition = "2024"

[dependencies]
base64 = "0.22"
clap = { version = "4.5.45", features = ["derive"] }
playwright = "0.0.20"
serde_json = "1.0.145"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tokio-stream = "0.1.17"
url = "2.5.7"
