[env]
RUST_LOG = "info,sqlx=warn,tower_http=info,eran_codes=debug"
DATABASE_URL = "postgres://app:app@localhost:5432/app"
HOST = "127.0.0.1"
PORT = "3002"
SESSION_SECRET = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
DATA_ENCRYPTION_KEY = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
RUSTC_WRAPPER = ""

[alias]
r = "run"
t = "test"
b = "build"
c = "check"
xfmt = "fmt --all"
xclippy = "clippy --all-targets --all-features"
with-db = "run --bin with_db --"
