[package]
name = "domain"
version = "0.1.1"
edition = "2024"

[dependencies]
nutype = { workspace = true, features = ["serde"] }
snafu = "0.9.0"
bon = { version = "3.9.1", features = [
  "experimental-overwritable",
  "experimental-getter",
  "implied-bounds",
] }
moddef = { workspace = true }
uuid = { version = "1.23.0", features = ["v4"] }
strum = { workspace = true }
strum_macros = { workspace = true }
email_address = "0.2.9"
serde = { version = "1.0.228", features = ["derive"] }
