[package]
name = "domain"
version = "0.1.1"
edition = "2024"

[dependencies]
nutype = { workspace = true }
snafu = "0.8.9"
bon = { version = "3.8.1", features = [
  "experimental-overwritable",
  "experimental-getter",
  "implied-bounds",
] }
moddef = { workspace = true }
uuid = { version = "1.12.1", features = ["v4"] }
strum = { workspace = true }
strum_macros = { workspace = true }
